/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package daily_diary;

import static daily_diary.Frontpage.DisplayPanel;
import static daily_diary.Frontpage.bt_login;
import static daily_diary.Frontpage.bt_notes;
import static daily_diary.Frontpage.bt_todo;
import static daily_diary.Frontpage.bt_signup;
import java.awt.CardLayout;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author avishkar
 */
public class Login extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    
    public static String user_login="";
    public static int login_status = 0;
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tf_Password = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_UserName = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);
        add(tf_Password);
        tf_Password.setBounds(290, 170, 170, 28);

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setText("Password");
        add(jLabel3);
        jLabel3.setBounds(110, 170, 97, 22);

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setText("User Name");
        add(jLabel2);
        jLabel2.setBounds(110, 120, 111, 22);

        tf_UserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_UserNameActionPerformed(evt);
            }
        });
        add(tf_UserName);
        tf_UserName.setBounds(290, 120, 170, 28);

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(290, 210, 90, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/daily_diary/rsz_login.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, -10, 680, 510);
    }// </editor-fold>//GEN-END:initComponents

    private void tf_UserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_UserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_UserNameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        Thread t = new Thread(){

            public void run(){

                try {
                    String li_UserName=tf_UserName.getText();
                    String li_Password=tf_Password.getText();
                    tf_UserName.setText("");
                    tf_Password.setText("");
                    Database_Server db= new Database_Server();
                    db.Start_Connection();
                    String sql = "SELECT Name,Password FROM User_Details";
                    ResultSet rs = db.stmt.executeQuery(sql);

                    boolean user_found = false;
                    boolean pass_match = false;

                    while(rs.next()){
                        
                        String user = rs.getString("Name");
                        String pass = rs.getString("Password");

                        if(user.equals(li_UserName)){
                            user_found=true;
                            if(pass.equals(li_Password))pass_match=true;
                        }
                        System.out.println(user + " " + pass);
                    }
                    if(user_found==true&&pass_match==true)
                    {
                        CardLayout card =(CardLayout) DisplayPanel.getLayout();
                        card.show(DisplayPanel, "home");
                        
                        JOptionPane.showMessageDialog(null,"LOGIN SUCESSFULL");
                        bt_notes.setVisible(true);
                        bt_todo.setVisible(true);
                        bt_signup.setVisible(false);
                        user_login=li_UserName.substring(0);
                        //Frontpage.bt_login.setVisible(false);
                        login_status = 1;
                        bt_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/daily_diary/rsz_user_logout.png")));
                    }
                    else{
                    
                         JOptionPane.showMessageDialog(null,"INCORRECT USERNAME OR PASSWORD");

                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                } 
            }
        };t.start();

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JPasswordField tf_Password;
    private javax.swing.JTextField tf_UserName;
    // End of variables declaration//GEN-END:variables
}
