/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package daily_diary;

import static daily_diary.Frontpage.DisplayPanel;
import java.awt.CardLayout;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author priyanja
 */
public class Sign_up extends javax.swing.JPanel {

    /**
     * Creates new form Sign_up
     */
    public Sign_up() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tf_Password = new javax.swing.JPasswordField();
        tf_ConfirmPassword = new javax.swing.JPasswordField();
        tf_UserName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_Email = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(1, 1, 1));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("USER NAME");
        add(jLabel1);
        jLabel1.setBounds(170, 120, 120, 18);
        add(tf_Password);
        tf_Password.setBounds(160, 350, 120, 28);
        add(tf_ConfirmPassword);
        tf_ConfirmPassword.setBounds(410, 350, 120, 28);

        tf_UserName.setBackground(new java.awt.Color(249, 165, 80));
        add(tf_UserName);
        tf_UserName.setBounds(160, 200, 120, 28);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel2.setText("PASSWORD");
        add(jLabel2);
        jLabel2.setBounds(170, 290, 120, 21);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel3.setText("CONFIRM PASSWORD");
        add(jLabel3);
        jLabel3.setBounds(370, 290, 210, 18);

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel4.setText("EMAIL");
        add(jLabel4);
        jLabel4.setBounds(430, 140, 80, 21);
        add(tf_Email);
        tf_Email.setBounds(410, 210, 110, 28);

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(440, 440, 120, 30);

        jLabel6.setBackground(new java.awt.Color(4, 3, 2));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/daily_diary/signup.jpg"))); // NOI18N
        add(jLabel6);
        jLabel6.setBounds(80, 10, 540, 490);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String username = tf_UserName.getText();
        String password = tf_Password.getText();
        String Con_Password = tf_ConfirmPassword.getText();
        String email = tf_Email.getText();
        
                if(username.equals("") || password.equals(""))
                {
                    JOptionPane.showMessageDialog(null,"One or more field is empty");
                }

                else if(!password.equals(Con_Password)){

                    tf_Password.setText("");
                    tf_ConfirmPassword.setText((""));
                    System.out.println("A");
                    JOptionPane.showMessageDialog(null,"PASSWORDS DO NOT MATCH");
                }
                else{
                    
                try {
                    Database_Server db = new Database_Server();
                    db.Start_Connection();
                    PreparedStatement ps = db.conn.prepareStatement("insert into User_Details (Name,Password, Email) values(?,?,?)");

                    ps.setString(1, username);
                    ps.setString(2, password);
                    ps.setString(3, email);
                    ps.executeUpdate();
                    
                    JOptionPane.showMessageDialog(null,"SIGNUP SUCCESSFULL");
                    
                    tf_UserName.setText("");
                    tf_Email.setText("");
                    tf_Password.setText("");
                    tf_ConfirmPassword.setText("");
                    
                    CardLayout Card = (CardLayout)DisplayPanel.getLayout();
    
                    Card.show(DisplayPanel, "home");
                
            } catch (SQLException ex) {
                Logger.getLogger(Sign_up.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Sign_up.class.getName()).log(Level.SEVERE, null, ex);
            }
                }
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField tf_ConfirmPassword;
    private javax.swing.JTextField tf_Email;
    private javax.swing.JPasswordField tf_Password;
    private javax.swing.JTextField tf_UserName;
    // End of variables declaration//GEN-END:variables
}
