/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package daily_diary;

import static daily_diary.Login.user_login;
import static daily_diary.Notes.tf_key;
import static daily_diary.Notes.tf_name;
import static daily_diary.Notes.tf_topic;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author avishkar
 */
public class Todo extends javax.swing.JPanel {

    /**
     * Creates new form Todo
     */
    public Todo() {
        initComponents();
    }
    public static ResultSet rs_list=null;
    public static String list_t = null;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bt_delete = new javax.swing.JButton();
        bt_add = new javax.swing.JButton();
        bt_save = new javax.swing.JButton();
        bt_savechanges = new javax.swing.JButton();
        bt_update = new javax.swing.JButton();
        tf_new = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_all = new javax.swing.JList();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        setLayout(null);

        bt_delete.setText("Delete");
        bt_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_deleteActionPerformed(evt);
            }
        });
        add(bt_delete);
        bt_delete.setBounds(510, 350, 130, 30);

        bt_add.setText("Add New");
        bt_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_addActionPerformed(evt);
            }
        });
        add(bt_add);
        bt_add.setBounds(520, 10, 110, 30);

        bt_save.setText("Save ");
        bt_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_saveActionPerformed(evt);
            }
        });
        add(bt_save);
        bt_save.setBounds(520, 120, 110, 30);

        bt_savechanges.setText("Save Changes");
        bt_savechanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_savechangesActionPerformed(evt);
            }
        });
        add(bt_savechanges);
        bt_savechanges.setBounds(520, 160, 108, 30);

        bt_update.setText("Update");
        bt_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_updateActionPerformed(evt);
            }
        });
        add(bt_update);
        bt_update.setBounds(510, 390, 130, 30);

        tf_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_newActionPerformed(evt);
            }
        });
        add(tf_new);
        tf_new.setBounds(30, 100, 470, 90);

        list_all.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list_allMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(list_all);

        add(jScrollPane1);
        jScrollPane1.setBounds(30, 220, 470, 200);

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(19, 7, 7));
        jLabel4.setText("TO DO LIST");
        add(jLabel4);
        jLabel4.setBounds(190, 30, 230, 30);

        jLabel1.setBackground(new java.awt.Color(241, 241, 49));
        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/daily_diary/rsz_xyz.jpg"))); // NOI18N
        jLabel1.setText("To Do List");
        add(jLabel1);
        jLabel1.setBounds(0, 0, 660, 490);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_addActionPerformed
        // TODO add your handling code here:
        
        tf_new.setEditable(true);
        tf_new.setText("");
        bt_save.setVisible(true);
        
    }//GEN-LAST:event_bt_addActionPerformed

    private void bt_savechangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_savechangesActionPerformed
        // TODO add your handling code here:
        Thread t = new Thread(){
        
            public void run(){
            
                try {
            // TODO add your handling code here:
            
            tf_new.setEditable(false);
           
            
            //bt_done.setVisible(false);
            
            //bt_save.setVisible(false);
            String list= tf_new.getText();
            long now = System.currentTimeMillis();
            java.util.Date d = new java.util.Date(now);
                    System.out.println("update");
            DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
               
            System.out.println("checking system status");
                
            String date =dateFormat.format(d).toString();
            Database_Server db = new Database_Server();
            db.Start_Connection();
            
            String sql ="Update List set list = '"+list+"',Date = '"+date+"' where User_name = '"+user_login+"'";
            db.stmt.executeUpdate(sql);
            tf_new.setText("");
            tf_new.setEditable(false);
            bt_add.setVisible(true);
            bt_savechanges.setVisible(false);
             Refresh_list();
                    System.out.println("update complete");
        } catch (SQLException ex) {
            Logger.getLogger(Notes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Notes.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            }
        
        
        };
        t.start();
    }//GEN-LAST:event_bt_savechangesActionPerformed

    private void bt_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_saveActionPerformed
        // TODO add your handling code here:
        Thread t = new Thread(){
        
            public void run(){
            
                try {
            // TODO add your handling code he
            String list= tf_new.getText();
             tf_new.setEditable(false);
            
            tf_new.setText("");
            
            bt_save.setVisible(false);
            long now = System.currentTimeMillis();
            java.util.Date d = new java.util.Date(now);
                
            DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
               
            System.out.println("checking system status");
                
            String date =dateFormat.format(d).toString();
            Database_Server db = new Database_Server();
            db.Start_Connection();
            
            String sql ="insert into List (list,User_name,date) values('"+list+"','"+user_login+"','"+date+"')";
            db.stmt.executeUpdate(sql);
            Refresh_list();

          
        } catch (SQLException ex) {
            Logger.getLogger(Notes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Notes.class.getName()).log(Level.SEVERE, null, ex);
        }
            
}
            };
        t.start();
    }
 public static void Refresh_list() {
                Thread t= new Thread(){
        
            public void run(){
                
                try {
                    Database_Server db = new Database_Server();
                    db.Start_Connection();
                    
                    String sql ="select * from List where User_name= '"+user_login+"'";
                   rs_list = db.stmt.executeQuery(sql);
                    
                    DefaultListModel kuchbhi = new DefaultListModel();
                    
                    
                    rs_list.beforeFirst();
                    while(rs_list.next()){
                    
                        String name = rs_list.getString("list");
                        kuchbhi.addElement(name);
                    }
                    
                    list_all.setModel(kuchbhi);
                    
                } catch (SQLException ex) {
                    Logger.getLogger(Notes.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Notes.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                
            
            }
        
        };
        t.start();//To change body of generated methods, choose Tools | Templates.
            
        
        
        
    }//GEN-LAST:event_bt_saveActionPerformed

    private void list_allMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_allMouseClicked
        // TODO add your handling code here:
        list_t = list_all.getSelectedValue().toString();
        bt_update.setVisible(true);
        bt_delete.setVisible(true);
    }//GEN-LAST:event_list_allMouseClicked

    private void bt_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_deleteActionPerformed
        try {
            // TODO add your handling code here:
            String del_list = list_t;
            Database_Server db1 = new Database_Server();
            db1.Start_Connection();
            
            String sql ="select * from List";
            rs_list = db1.stmt.executeQuery(sql);
            while(rs_list.next())
            {
                if(rs_list.getString("list").equals(del_list))
                {
                    String sql2 = "DELETE FROM List where list = '"+del_list+"' ";
                     Database_Server db = new Database_Server();
                      db.Start_Connection();
            
                    db.stmt.executeUpdate(sql2);
                }
            }
            Refresh_list();
        } catch (SQLException ex) {
            Logger.getLogger(Todo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Todo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_bt_deleteActionPerformed

    private void bt_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_updateActionPerformed
        // TODO add your handling code here:
        tf_new.setEditable(true);
        tf_new.setText(list_t);
        bt_savechanges.setVisible(true);
        bt_save.setVisible(false);
        bt_add.setVisible(false);
        bt_update.setVisible(false);
        
    }//GEN-LAST:event_bt_updateActionPerformed

    private void tf_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_newActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_newActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton bt_add;
    public static javax.swing.JButton bt_delete;
    public static javax.swing.JButton bt_save;
    public static javax.swing.JButton bt_savechanges;
    public static javax.swing.JButton bt_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JList list_all;
    public static javax.swing.JTextField tf_new;
    // End of variables declaration//GEN-END:variables
}
